version = 0.1
[default.deploy.parameters]
stack_name = "FuegoQuasar-deploy-app"
resolve_s3 = true
s3_prefix = "FuegoQuasar-deploy-app"
region = "g"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
