// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fuego-quasar-app/internal/core/application/service"
	"fuego-quasar-app/internal/infrastructure/awsSecret"
	"fuego-quasar-app/internal/infrastructure/mongodb"
	"fuego-quasar-app/internal/infrastructure/repository"
	"fuego-quasar-app/internal/interfaces/handler"
)

// Injectors from wire.go:

func InitializeMyService() handler.LambdaHandler {
	triangulationService := service.NewTriangulationService()
	decodeMessageService := service.NewDecodeMessageService()
	secretManagerService := awsSecret.NewAWSSecretManagerService()
	client := mongodb.NewMongoClient(secretManagerService)
	satelliteRepository := repository.NewSatelliteRepositoryMongo(client)
	fuegoQuasarService := service.NewFuegoQuasarService(satelliteRepository, decodeMessageService, triangulationService)
	lambdaHandler := handler.NewLambdaHandler(triangulationService, decodeMessageService, secretManagerService, satelliteRepository, fuegoQuasarService)
	return lambdaHandler
}
