// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"fuego-quasar-app/internal/core/application/service"
	"fuego-quasar-app/internal/interfaces/handler"
)

// Injectors from wire.go:

func InitializeMyService() handler.LambdaHandler {
	triangulationService := service.NewTriangulationService()
	lambdaHandler := handler.NewLambdaHandler(triangulationService)
	return lambdaHandler
}
