name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
 
permissions:
  contents: read

jobs:
  unit_Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.6']

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
        
      - name: Install dependencies
        run: |
          cd ./fuego-quasar-app
          ls
          go get .
        
      
      - name: Test with Go
        run: |
          run: cd ./fuego-quasar-app/
          go test -json > TestResults-${{ matrix.go-version }}.json
          
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json
  deploy:
    name: Deploy
    needs: unit_Test
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - run: sam build --use-container
    - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
  test-api:
    name: test
    needs: deploy
    runs-on: ubuntu-latest
    steps:     
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: "16.x"
    
    #Install the Newman command line utility, the html extra
    - name: Install Newman
      run: |
        npm install -g newman
    #Install the Newman command  html extra
    - name:  Install HTMLReporter
      run: |
        npm install -g newman-reporter-htmlextra

    #Run the POSTMAN Collection
    - name: Run Postman Collection
      env:
        TEST: sdsadasd
        #COLLECTION_UID: ${{secrets.COLLECTION_UID}} ENVIRONMENT_UID: ${{secrets.ENVIRONMENT_UID}}
        API_KEY: ${{secrets.PostmanKey}}
        
      run: |
        newman run https://api.getpostman.com/collections/2242228-bbadee89-3d1d-434b-bb27-4220d2738fda/?apikey=$API_KEY –environment https://api.getpostman.com/environments/2242228-c25adb19-d282-4e15-ba47-4a3fec9549c3/?apikey=$API_KEY –suppress-exit-code -r 'cli,htmlextra'  
        
    
    #Upload the contents of Test Results directory to workspace
    - name: Output the Result Details
      uses: actions/upload-artifact@v2
      with:
        name: RunReports
        path: newman
